### PR TITLE
Edit index file

### PR DESCRIPTION
**Pull request by JeffreyMcCraney**

### CODE REVIEW

**Comment by andreruffert** [comment]
@JeffreyMcCraney is this a serious pr? :flushed:

**Comment by JeffreyMcCraney** [comment]
@andreruffert not in the slightest. I'm new too github and accidentally did that while just messing around with the code. I deleted my forked repository thinking it would delete the PR. Sorry!  Learning curves... 😳

**Comment by JeffreyMcCraney** [comment]
Sorry about the confusion!

**Comment by andreruffert** [comment]
Hehe ok no problem :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
