### PR TITLE
Added an option called hideinput that allows having the HTML <input> field the slider controls visible

### PR DESCRIPTION
**Pull request by kshade**
Really small change, I've also changed the slider objects to appear before, instead of after, the <input> element because I think that looks better if you want to have both visible.

### CODE REVIEW

**Comment by andreruffert** [comment]
@kshade thanks for your PR but I don't see it as a feature of the plugin.

What is your usecase for this?

**Comment by kshade** [comment]
I'm building a website with multiple sliders per page that replaces an older one with only numeric input. The input is a bit like that of an audio mixer. I know that some users will prefer directly inputting numbers, and that copy/paste functionality is desired. I also believe that this is the simplest way to have the exact number selected displayed while also improving accessibility.

**Comment by andreruffert** [comment]
K I see. Have a look at this [codepen](https://codepen.io/andreruffert/pen/vOVygB?editors=0110) it's kinda another approach to yours...

✌️

**Comment by kshade** [comment]
That adds unnecessary JS and HTML.

**Pull request closed without merging**
