### PR TITLE
Update rangeslider.js

### PR DESCRIPTION
**Pull request by paulitto**

### CODE REVIEW

**Comment by andreruffert** [comment]
What is the reason for this change?
The polyfill wouldn't be executed if there is no `input type="range"` support.
This makes no sense to me!

**Comment by paulitto** [comment]
@andreruffert  right, I just think input range variable here returns true in case we do have type="range" support, so we need to exit if its false.
I tried rangeslider some time ago for one of my projects, and it didnt work for me without this small change, exited all the time in this place...

**Comment by andreruffert** [comment]
K. So I guess you didn't want to use it as polyfill which means for all Browsers also if they have native `input type="range"` support. For this there is a option `polyfill` which you can set to `false` and it should work without any additional changes.
````
$('input[type="range"]').rangeslider({
    polyfill: false
});
````

**Comment by paulitto** [comment]
you are right, looks like I didnt understand the polyfill option, thanks for the explanation!

**Comment by andreruffert** [comment]
@paulitto  you're welcome :ok_hand::v:

**Pull request closed without merging**
